ROOT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
PRIOR_DIRECTORY=$ROOT_DIRECTORY/deep_prior
export PATH=$ROOT_DIRECTORY:$PRIOR_DIRECTORY:$PATH
export PYTHONPATH=$ROOT_DIRECTORY:$PRIOR_DIRECTORY:$PYTHONPATH

source $ROOT_DIRECTORY/venv/bin/activate
